# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

title: "Richard Westenra | Web designer &amp; front-end developer"
description: "London-based web developer with a passion for making beautiful websites, interactive webapps &amp; data-vis. This is my portfolio &amp; blog."
author:
  name: Richard Westenra
  email: rjwestenra@gmail.com

# Grunt handles images and assets.
exclude: ['img', 'css', 'js', 'fonts',
          '**.ico', 'node_modules']

include: ['.htaccess','**.ico','**.xml', 'CNAME']

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true

# Markdown library
markdown: redcarpet
#   extensions: ['fenced_code_blocks', 'smart']

highlighter: pygments

permalink: :title/

relative_permalinks: false

liveUrl: "http://richardwestenra.com/"

env: local

baseurl: "/"
