# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

title: "Richard Westenra | Creative front-end developer"
description: "Christchurch-based web developer with a passion for making beautiful websites, interactive webapps &amp; data-viz. This is my portfolio &amp; blog."
author:
  name: Richard Westenra
  email: rjwestenra@gmail.com

# Grunt handles images and assets.
exclude: ['img', 'css', 'js', 'fonts',
          '**.ico', 'node_modules']

include: ['.htaccess','**.ico','**.xml', 'CNAME']

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true

markdown: kramdown

highlighter: rouge

permalink: :title/

relative_permalinks: false

liveUrl: "https://www.richardwestenra.com/"

env: local
